---
apiVersion: v1
kind: Pod
metadata:
  name: hasura-pod
  labels:
    app: hasura
spec:
  containers:
    - name: hasura-pod
      image: hasura/graphql-engine
      env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://postgres:z8V2byBL2H@postgress-postgresql.default.svc.cluster.local:5432/postgres
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: 'true'
      ports:
        - containerPort: 8080
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: svc-hasura
spec:
  selector:
    app: hasura
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: hasura
  name: ingress-hasura
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: svc-hasura
                port:
                  number: 8080
            path: /
            pathType: Prefix