---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: "standart"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloword-deployment
spec:
  selector:
    matchLabels:
      app: helloword
  replicas: 1
  template:
    metadata:
      labels:
        app: helloword
    spec:
      containers:
        - name: k8s-demo
          image: wardviaene/k8s-demo
          ports:
            - containerPort: 3000
              name: nodejs-port
          volumeMounts:
            - mountPath: /myvol
              name: myvolume
      volumes:
        - name: myvolume
          awsElasticBlockStore:
            volumeID: 355as25 # Insert id volume here (It is a number example)

