---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-render
rules:
  - apiGroups: [""]
    resources:
      - pods
      - secrets
    verbs:
      - get
      - watch
      - list