Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.synced_folder "../", "/home/vagrant/k8sCurso"
  config.vm.define "awsK8sCurso"
  config.vm.hostname = "awsK8sCurso"
  config.vm.network :private_network, ip: "192.168.33.27"

  config.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "kopsInstall.yml"
      ansible.become = true
      ansible.groups = {
        "kops" => ["awsK8sCurso"]
      }
  end

end
