apiVersion: v1
kind: Service
metadata:
        name: magicbar-service
spec:
        ports:
                - port: 31001
                  nodePort: 31001
                  targetPort: nodejs-port
                  protocol: TCP
        selector:
                app: magicbar
        type: NodePort
