---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: myspace
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 521Mi
      defaultRequest:
        cpu: 100m
        memory: 256Mi