apiVersion: v1
kind: Service
metadata:
        name: magicbar-service
spec:
        ports:
          - port: 80
            targetPort: nodejs-port
            protocol: TCP
        selector:
            app: magicbar-deployment-59bb568776
        type: LoadBalancer
