---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  labels:
    app: helloword
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: helloword-export
  labels:
    app: helloword
spec:
  type: NodePort
  selector:
    app: helloword
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

#
#---
#apiVersion: v1
#kind: ReplicationController
#spec:
#  replicas: 4
#  selector:
#    app: helloword
#  template:
#    metadata:
#      labels:
#        app: helloword
#    spec:
#      containers:
#        - name: task-pv-container
#          image: nginx
#          ports:
#            - containerPort: 80
#              name: "http-server"
#          volumeMounts:
#            - mountPath: "/usr/share/nginx/html"
#              name: task-pv-storage