---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "standart"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi