apiVersion: v1
kind: Service
metadata:
  name: nodeport-demo
spec:
  selector:
    app: k8s-mostela
  type: NodePort
  ports:
    - port: 80
      nodePort: 31720
      targetPort: ex-web-k8s
      protocol: TCP
