apiVersion: v1
kind: Service
metadata:
  name: k8s-mostela-service
  labels:
    app: k8s-mostela
spec:
  selector:
    app: k8s-mostela
  ports:
    - port: 80
      name: ex-web-k8s
      protocol: TCP
  type: LoadBalancer