---
apiVersion: v1
kind: Service
metadata:
  name: k8s-mostela-service
  namespace: example-k8s
  labels:
    app: k8s-mostela
spec:
  selector:
    app: k8s-mostela
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31720
      name: ex-web-k8s
      protocol: TCP
  type: LoadBalancer