---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: mostela.com
  dnsNames:
    - mostela.com
  issuerRef:
    name: ca-issuer
    kind: Issuer