apiVersion: v1
kind: Pod
metadata:
  name: nodeexample.helloword.com
  labels:
    app: helloword
spec:
  containers:
    - name: k8s-demo
      image: wardviaene/k8s-demo
      ports:
        - containerPort: 3000
      volumeMounts:
        - mountPath: /etc/config
          name: config-volume
  volumes:
    - name: config-volume
      configMap:
        name: app-config